---
# tasks file for nginx_rol
- name: intsall nginx
  yum: name=nginx state=latest

- name: copy index.html template
  template:
          src: index.html
          dest: /usr/share/nginx/html
  notify: restart nginx

- name: enable and start service
  service: 
      name: nginx
      enabled: yes
      state: started

